#! /bin/zsh
source ~/.zplug/init.zsh

zplug "MichaelAquilina/zsh-history-substring-search"
zplug "MichaelAquilina/zsh-syntax-highlighting", defer:2
zplug "MichaelAquilina/zsh-completions"
zplug "MichaelAquilina/zsh-emojis"
zplug "MichaelAquilina/zsh-autosuggestions"
export AUTOSWITCH_DEFAULTENV="default3"
zplug "MichaelAquilina/zsh-autoswitch-virtualenv"
zplug "MichaelAquilina/agnoster-zsh-theme", as:theme

zplug "lib/completion", from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

# Infinite History
export HISTSIZE="999999999999999"
export HISTFILESIZE="-1"

setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY_TIME

PREFERRED_HISTFILE="$HOME/Personal/zsh_history"
if [[ -f "$PREFERRED_HISTFILE" ]]; then
  export HISTFILE="$PREFERRED_HISTFILE"
fi

# show ISO8601 timestamp with history
alias history="fc -li 1"

VIRTUALENVWRAPPER="/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
if [[ -f "$VIRTUALENVWRAPPER" ]]; then
  source "$VIRTUALENVWRAPPER"
  workon default3
fi

# Fix VTE Configuration Issues when using Tilix
# https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue#user-content-1-source-vtesh-in-bashrc
if [[ $TILIX_ID ]]; then
  source /etc/profile.d/vte.sh
fi

# Source any additional configuration specific to this machine
if [[ -f ~/.machinerc.gpg ]]; then
  eval "$(gpg -d --no-tty ~/.machinerc.gpg 2>/dev/null)"
elif [[ -f ~/.machinerc ]]; then
  source ~/.machinerc
fi

if [[ -f ~/.github ]]; then
  export GITHUB_TOKEN="$(cat ~/.github)"
fi

cat ~/.crypto_squirrel

eval $(dircolors ~/.dircolors)

# Disable ansible from using cowsay
export ANSIBLE_NOCOWS=1

# Allow ctrl+left and ctrl+right movement
bindkey ';5D' emacs-backward-word
bindkey ';5C' emacs-forward-word

export WORDCHARS=''

setopt extended_glob

export PAGER="most"
export EDITOR="vim"

# Use pushd instead of cd
setopt AUTO_PUSHD
setopt PUSHD_SILENT

############################
#        FUNCTIONS         #
############################

# Synchronise pass account
function psync() {
  pass git pull origin master
  pass git push origin master
  pass git push backup master
}

# Enable 256 color mode
export TERM="xterm-256color"

function whatismyip() {
  curl ifconfig.co -s --connect-timeout 1
}

# Recursively list all values in gsettings
function all_gsettings() {
  for schema in $(gsettings list-schemas)
  do
      gsettings list-recursively "$schema"
  done
}

function color_cheatsheet() {
   x=`tput op`
   y=`printf %$((${COLUMNS}-6))s`
   for i in {0..256}; do
     o=00$i
     echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x
   done
}

function clean_branches() {
  IFS=$'\n'
  for item in $(git branch --merged master | grep -v master)
  do
    git branch -d "${item:2}"
  done
}


function notify() {
  # Used to notify you when a command has completed
  # example:  my-long-running-task | notify
  start_time="$(date +%s)"
  while read line
  do
    echo "$line"
  done <&0
  end_time="$(date +%s)"
  runtime="$((end_time-start_time))"
  notify-send "Command Completed in $runtime seconds!"
}

function flush_gpg_passwords() {
  echo RELOADAGENT | gpg-connect-agent
}


############################
#         ALIASES          #
############################

alias h="history"
alias -g NE="2>/dev/null"

# Grep Aliases
alias g="grep"
alias ig="grep -i"

alias ls="ls --color=auto"
alias ll="ls -lh --group-directories-first"
alias l="ls -lah --group-directories-first"

alias shrug='echo $em_shrug'

# Git Aliases
alias gs="git status"
alias gc="git commit"
alias gca="git commit --amend"
alias gco="git checkout"
alias gap="git add -p"
alias gpl="git pull"
alias gr="git rebase"
alias gst="git stash"
alias gpum="git pull upstream master"
alias gd="git diff"

export GH="git@github.com:MichaelAquilina"
export GL="git@gitlab.com:Aquilina"
export BB="git@bitbucket.org:maquilina"

# Tig Aliases
alias ta="tig --all"
alias t="tig"

# Vagrant Aliases
alias vs="vagrant ssh"
alias vc="vagrant ssh -c"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vp="vagrant provision"

# Docker Aliases
alias dcr="docker-compose run"

# Utilities
alias pm="pygmentize"
alias xopen="xdg-open"
alias LS="LS -e"  # Allow interrupt by Ctrl+C
alias explore="nautilus"
alias xcopy="xsel -i -b"
alias xpaste="xsel -o -b"
alias xc="xcopy"
alias xp="xpaste"

alias plog='pass git log --pretty="format:%C(bold) %G? %C(cyan) %ai %C(bold yellow)%s"'

alias cb="clean_branches"

# Weather in London
alias weather="curl wttr.in/London"

export PATH="$HOME/.yarn/bin:$PATH"
