- name: Setup Atom NPM package Dependencies
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - dockerlint

- name: Setup Atom Packages
  apm:
    name: "{{ item }}"
  loop:
    - an-old-hope-syntax
    - atom-beautify
    - atom-dark-fusion-syntax
    - atom-jinja2
    - atom-material-syntax
    - autocomplete-python
    - better-window-title
    - blame
    - color-picker
    - copy-tools
    - dash
    - file-icons
    - firewatch-syntax
    - git-time-machine
    - highlight-selected
    - hyperclick
    - keybinding-cheatsheet
    - language-babel
    - language-d
    - language-docker
    - language-protobuf
    - language-r
    - language-restructuredtext
    - language-swift
    - language-vala
    - last-cursor-position
    - linter
    - linter-docker
    - linter-flake8
    - linter-flow
    - linter-shellcheck
    - nucleus-dark-ui
    - pdf-view
    - pigments
    - python-isort
    - python-tools
    - sort-lines
    - tab-title

- name: Setup Atom configuration
  file:
    dest: "{{ item.dest }}"
    force: yes
    state: link
    src: "{{ item.src }}"
  loop:
    - {src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_config.cson", dest: ~/.atom/config.cson}
    - {src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_keymap.cson", dest: ~/.atom/keymap.cson}
    - {src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_snippets.cson", dest: ~/.atom/snippets.cson}
    - {src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_init.js", dest: ~/.atom/init.js}
    - {src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_styles.less", dest: ~/.atom/styles.less}
