- name: Add Additional APT Keys
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  loop: "{{ ui_apt_keys }}"

- name: Add Additional APT Repostories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ ui_apt_repos }}"

- name: Install Development APT Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  loop: "{{ development_packages }}"

- name: Install Other APT Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  loop: "{{ other_packages }}"

- name: Tomboy is removed
  become: yes
  apt:
    pkg: tomboy
    state: absent

- name: Make sure Flash player is uninstalled
  become: yes
  apt:
    pkg: flashplugin-installer
    state: absent

- name: Set file type associations
  file:
    state: link
    src: "{{ ansible_env.PWD }}/roles/gnome/files/mimeapps.list"
    dest: ~/.config/mimeapps.list
    force: yes

- name: Set Tilix as Default Terminal
  gsettings:
    schema: org.gnome.desktop.default-applications.terminal
    key: exec
    value: tilix

- name: local applications directory
  file:
    state: directory
    dest: "~/.local/share/applications"

- name: Setup lnav shortcut
  file:
    state: link
    force: yes
    src: "{{ ansible_env.PWD }}/roles/gnome/files/lnav.desktop"
    dest: "~/.local/share/applications/lnav.desktop"

- name: Meld Settings
  gsettings:
    schema: org.gnome.meld
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: highlight-syntax, value: "true"}
    - {key: style-scheme, value: "cobalt"}
    - {key: show-line-numbers, value: "true"}

- include_tasks: wireshark.yml

- include_tasks: zim.yml

- include_tasks: atom.yml

- include_tasks: redshift.yml

- include_tasks: terminator.yml

- include_tasks: powersettings.yml
