- name: Install GPG2
  become: yes
  apt:
    name: gnupg2
    state: latest

- name: Disable Gnome Keyring for GPG
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  with_items:
     - /etc/xdg/autostart/gnome-keyring-gpg.desktop
     - /usr/share/upstart/sessions/gnome-keyring-gpg.conf

- name: Create GNUPG Directory
  file:
    state: directory
    mode: 0700
    path: ~/.gnupg
